"""add bytes belief set representation

Revision ID: 0cc85fd39258
Revises: c2d4d3c3f862
Create Date: 2023-12-09 10:31:26.723568

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0cc85fd39258"
down_revision: Union[str, None] = "c2d4d3c3f862"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "belief_sets", sa.Column("representation", sa.LargeBinary(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("belief_sets", "representation")
    # ### end Alembic commands ###
