"""fix-plan

Revision ID: 40a92857b01e
Revises: 66831e2f475b
Create Date: 2023-11-18 09:44:54.816414

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "40a92857b01e"
down_revision: Union[str, None] = "66831e2f475b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
