"""add event game_dump

Revision ID: c258abd161e8
Revises: 3fdd264a47e2
Create Date: 2023-11-08 17:31:36.256747

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c258abd161e8"
down_revision: Union[str, None] = "3fdd264a47e2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("events", sa.Column("game_dump", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("events", "game_dump")
    # ### end Alembic commands ###
