"""add-plan

Revision ID: 66831e2f475b
Revises: 8d222deca6aa
Create Date: 2023-11-18 09:43:18.504646

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "66831e2f475b"
down_revision: Union[str, None] = "8d222deca6aa"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "plans",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("belief_set_input_id", sa.Integer(), nullable=False),
        sa.Column("belief_set_output_id", sa.Integer(), nullable=False),
        sa.Column("experiment_id", sa.Integer(), nullable=False),
        sa.Column("prompt_template_id", sa.Integer(), nullable=False),
        sa.Column("prompt", sa.String(), nullable=False),
        sa.Column("checkpoint_id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["belief_set_input_id"],
            ["belief_sets.belief_set_id"],
        ),
        sa.ForeignKeyConstraint(
            ["belief_set_output_id"],
            ["belief_sets.belief_set_id"],
        ),
        sa.ForeignKeyConstraint(
            ["checkpoint_id"],
            ["checkpoints.checkpoint_id"],
        ),
        sa.ForeignKeyConstraint(
            ["experiment_id"],
            ["experiments.experiment_id"],
        ),
        sa.ForeignKeyConstraint(
            ["prompt_template_id"],
            ["prompt_templates.prompt_template_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("plans")
    # ### end Alembic commands ###
