"""add-actions-to-plan

Revision ID: c2d4d3c3f862
Revises: 40a92857b01e
Create Date: 2023-11-26 15:33:09.605743

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c2d4d3c3f862"
down_revision: Union[str, None] = "40a92857b01e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("plans", sa.Column("actions", sa.String(), nullable=True))
    op.execute(
        """
        UPDATE plans
        SET actions = ''
        """
    )
    op.alter_column("plans", "actions", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("plans", "actions")
    # ### end Alembic commands ###
